services:
  - type: web
    name: email-scraper
    env: docker
    plan: starter
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: 10000
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome-stable"
      - key: CHROME_PATH
        value: "/usr/bin/google-chrome-stable"
      - key: NODE_ENV
        value: "production"
      - key: SUPABASE_KEY
        sync: false
